export interface CountryCode {
	code: string; // 如 "+86"
	country: string; // 国家/地区名称
	iso: string; // ISO 3166-1 alpha-2 代码
}

export const countryCodes: CountryCode[] = [
	// 常用地区（排在前面）
	{ code: "+86", country: "中国大陆", iso: "CN" },
	{ code: "+852", country: "香港", iso: "HK" },
	{ code: "+853", country: "澳门", iso: "MO" },
	{ code: "+886", country: "台湾", iso: "TW" },
	{ code: "+65", country: "新加坡", iso: "SG" },
	{ code: "+1", country: "美国/加拿大", iso: "US" },
	{ code: "+44", country: "英国", iso: "GB" },
	{ code: "+81", country: "日本", iso: "JP" },
	{ code: "+82", country: "韩国", iso: "KR" },

	// 其他地区（按字母顺序）
	{ code: "+93", country: "阿富汗", iso: "AF" },
	{ code: "+355", country: "阿尔巴尼亚", iso: "AL" },
	{ code: "+213", country: "阿尔及利亚", iso: "DZ" },
	{ code: "+376", country: "安道尔", iso: "AD" },
	{ code: "+244", country: "安哥拉", iso: "AO" },
	{ code: "+54", country: "阿根廷", iso: "AR" },
	{ code: "+374", country: "亚美尼亚", iso: "AM" },
	{ code: "+61", country: "澳大利亚", iso: "AU" },
	{ code: "+43", country: "奥地利", iso: "AT" },
	{ code: "+994", country: "阿塞拜疆", iso: "AZ" },
	{ code: "+973", country: "巴林", iso: "BH" },
	{ code: "+880", country: "孟加拉国", iso: "BD" },
	{ code: "+375", country: "白俄罗斯", iso: "BY" },
	{ code: "+32", country: "比利时", iso: "BE" },
	{ code: "+501", country: "伯利兹", iso: "BZ" },
	{ code: "+229", country: "贝宁", iso: "BJ" },
	{ code: "+975", country: "不丹", iso: "BT" },
	{ code: "+591", country: "玻利维亚", iso: "BO" },
	{ code: "+387", country: "波黑", iso: "BA" },
	{ code: "+267", country: "博茨瓦纳", iso: "BW" },
	{ code: "+55", country: "巴西", iso: "BR" },
	{ code: "+673", country: "文莱", iso: "BN" },
	{ code: "+359", country: "保加利亚", iso: "BG" },
	{ code: "+226", country: "布基纳法索", iso: "BF" },
	{ code: "+257", country: "布隆迪", iso: "BI" },
	{ code: "+855", country: "柬埔寨", iso: "KH" },
	{ code: "+237", country: "喀麦隆", iso: "CM" },
	{ code: "+238", country: "佛得角", iso: "CV" },
	{ code: "+236", country: "中非共和国", iso: "CF" },
	{ code: "+235", country: "乍得", iso: "TD" },
	{ code: "+56", country: "智利", iso: "CL" },
	{ code: "+57", country: "哥伦比亚", iso: "CO" },
	{ code: "+269", country: "科摩罗", iso: "KM" },
	{ code: "+242", country: "刚果共和国", iso: "CG" },
	{ code: "+243", country: "刚果民主共和国", iso: "CD" },
	{ code: "+506", country: "哥斯达黎加", iso: "CR" },
	{ code: "+385", country: "克罗地亚", iso: "HR" },
	{ code: "+53", country: "古巴", iso: "CU" },
	{ code: "+357", country: "塞浦路斯", iso: "CY" },
	{ code: "+420", country: "捷克", iso: "CZ" },
	{ code: "+45", country: "丹麦", iso: "DK" },
	{ code: "+253", country: "吉布提", iso: "DJ" },
	{ code: "+593", country: "厄瓜多尔", iso: "EC" },
	{ code: "+20", country: "埃及", iso: "EG" },
	{ code: "+503", country: "萨尔瓦多", iso: "SV" },
	{ code: "+240", country: "赤道几内亚", iso: "GQ" },
	{ code: "+291", country: "厄立特里亚", iso: "ER" },
	{ code: "+372", country: "爱沙尼亚", iso: "EE" },
	{ code: "+251", country: "埃塞俄比亚", iso: "ET" },
	{ code: "+679", country: "斐济", iso: "FJ" },
	{ code: "+358", country: "芬兰", iso: "FI" },
	{ code: "+33", country: "法国", iso: "FR" },
	{ code: "+241", country: "加蓬", iso: "GA" },
	{ code: "+220", country: "冈比亚", iso: "GM" },
	{ code: "+995", country: "格鲁吉亚", iso: "GE" },
	{ code: "+49", country: "德国", iso: "DE" },
	{ code: "+233", country: "加纳", iso: "GH" },
	{ code: "+30", country: "希腊", iso: "GR" },
	{ code: "+502", country: "危地马拉", iso: "GT" },
	{ code: "+224", country: "几内亚", iso: "GN" },
	{ code: "+245", country: "几内亚比绍", iso: "GW" },
	{ code: "+592", country: "圭亚那", iso: "GY" },
	{ code: "+509", country: "海地", iso: "HT" },
	{ code: "+504", country: "洪都拉斯", iso: "HN" },
	{ code: "+36", country: "匈牙利", iso: "HU" },
	{ code: "+354", country: "冰岛", iso: "IS" },
	{ code: "+91", country: "印度", iso: "IN" },
	{ code: "+62", country: "印度尼西亚", iso: "ID" },
	{ code: "+98", country: "伊朗", iso: "IR" },
	{ code: "+964", country: "伊拉克", iso: "IQ" },
	{ code: "+353", country: "爱尔兰", iso: "IE" },
	{ code: "+972", country: "以色列", iso: "IL" },
	{ code: "+39", country: "意大利", iso: "IT" },
	{ code: "+225", country: "科特迪瓦", iso: "CI" },
	{ code: "+1876", country: "牙买加", iso: "JM" },
	{ code: "+962", country: "约旦", iso: "JO" },
	{ code: "+7", country: "哈萨克斯坦", iso: "KZ" },
	{ code: "+254", country: "肯尼亚", iso: "KE" },
	{ code: "+686", country: "基里巴斯", iso: "KI" },
	{ code: "+965", country: "科威特", iso: "KW" },
	{ code: "+996", country: "吉尔吉斯斯坦", iso: "KG" },
	{ code: "+856", country: "老挝", iso: "LA" },
	{ code: "+371", country: "拉脱维亚", iso: "LV" },
	{ code: "+961", country: "黎巴嫩", iso: "LB" },
	{ code: "+266", country: "莱索托", iso: "LS" },
	{ code: "+231", country: "利比里亚", iso: "LR" },
	{ code: "+218", country: "利比亚", iso: "LY" },
	{ code: "+423", country: "列支敦士登", iso: "LI" },
	{ code: "+370", country: "立陶宛", iso: "LT" },
	{ code: "+352", country: "卢森堡", iso: "LU" },
	{ code: "+261", country: "马达加斯加", iso: "MG" },
	{ code: "+265", country: "马拉维", iso: "MW" },
	{ code: "+60", country: "马来西亚", iso: "MY" },
	{ code: "+960", country: "马尔代夫", iso: "MV" },
	{ code: "+223", country: "马里", iso: "ML" },
	{ code: "+356", country: "马耳他", iso: "MT" },
	{ code: "+692", country: "马绍尔群岛", iso: "MH" },
	{ code: "+222", country: "毛里塔尼亚", iso: "MR" },
	{ code: "+230", country: "毛里求斯", iso: "MU" },
	{ code: "+52", country: "墨西哥", iso: "MX" },
	{ code: "+691", country: "密克罗尼西亚", iso: "FM" },
	{ code: "+373", country: "摩尔多瓦", iso: "MD" },
	{ code: "+377", country: "摩纳哥", iso: "MC" },
	{ code: "+976", country: "蒙古", iso: "MN" },
	{ code: "+382", country: "黑山", iso: "ME" },
	{ code: "+212", country: "摩洛哥", iso: "MA" },
	{ code: "+258", country: "莫桑比克", iso: "MZ" },
	{ code: "+95", country: "缅甸", iso: "MM" },
	{ code: "+264", country: "纳米比亚", iso: "NA" },
	{ code: "+674", country: "瑙鲁", iso: "NR" },
	{ code: "+977", country: "尼泊尔", iso: "NP" },
	{ code: "+31", country: "荷兰", iso: "NL" },
	{ code: "+64", country: "新西兰", iso: "NZ" },
	{ code: "+505", country: "尼加拉瓜", iso: "NI" },
	{ code: "+227", country: "尼日尔", iso: "NE" },
	{ code: "+234", country: "尼日利亚", iso: "NG" },
	{ code: "+850", country: "朝鲜", iso: "KP" },
	{ code: "+47", country: "挪威", iso: "NO" },
	{ code: "+968", country: "阿曼", iso: "OM" },
	{ code: "+92", country: "巴基斯坦", iso: "PK" },
	{ code: "+680", country: "帕劳", iso: "PW" },
	{ code: "+507", country: "巴拿马", iso: "PA" },
	{ code: "+675", country: "巴布亚新几内亚", iso: "PG" },
	{ code: "+595", country: "巴拉圭", iso: "PY" },
	{ code: "+51", country: "秘鲁", iso: "PE" },
	{ code: "+63", country: "菲律宾", iso: "PH" },
	{ code: "+48", country: "波兰", iso: "PL" },
	{ code: "+351", country: "葡萄牙", iso: "PT" },
	{ code: "+974", country: "卡塔尔", iso: "QA" },
	{ code: "+40", country: "罗马尼亚", iso: "RO" },
	{ code: "+7", country: "俄罗斯", iso: "RU" },
	{ code: "+250", country: "卢旺达", iso: "RW" },
	{ code: "+685", country: "萨摩亚", iso: "WS" },
	{ code: "+378", country: "圣马力诺", iso: "SM" },
	{ code: "+966", country: "沙特阿拉伯", iso: "SA" },
	{ code: "+221", country: "塞内加尔", iso: "SN" },
	{ code: "+381", country: "塞尔维亚", iso: "RS" },
	{ code: "+248", country: "塞舌尔", iso: "SC" },
	{ code: "+232", country: "塞拉利昂", iso: "SL" },
	{ code: "+421", country: "斯洛伐克", iso: "SK" },
	{ code: "+386", country: "斯洛文尼亚", iso: "SI" },
	{ code: "+677", country: "所罗门群岛", iso: "SB" },
	{ code: "+252", country: "索马里", iso: "SO" },
	{ code: "+27", country: "南非", iso: "ZA" },
	{ code: "+82", country: "韩国", iso: "KR" },
	{ code: "+211", country: "南苏丹", iso: "SS" },
	{ code: "+34", country: "西班牙", iso: "ES" },
	{ code: "+94", country: "斯里兰卡", iso: "LK" },
	{ code: "+249", country: "苏丹", iso: "SD" },
	{ code: "+597", country: "苏里南", iso: "SR" },
	{ code: "+268", country: "斯威士兰", iso: "SZ" },
	{ code: "+46", country: "瑞典", iso: "SE" },
	{ code: "+41", country: "瑞士", iso: "CH" },
	{ code: "+963", country: "叙利亚", iso: "SY" },
	{ code: "+992", country: "塔吉克斯坦", iso: "TJ" },
	{ code: "+255", country: "坦桑尼亚", iso: "TZ" },
	{ code: "+66", country: "泰国", iso: "TH" },
	{ code: "+670", country: "东帝汶", iso: "TL" },
	{ code: "+228", country: "多哥", iso: "TG" },
	{ code: "+676", country: "汤加", iso: "TO" },
	{ code: "+216", country: "突尼斯", iso: "TN" },
	{ code: "+90", country: "土耳其", iso: "TR" },
	{ code: "+993", country: "土库曼斯坦", iso: "TM" },
	{ code: "+688", country: "图瓦卢", iso: "TV" },
	{ code: "+256", country: "乌干达", iso: "UG" },
	{ code: "+380", country: "乌克兰", iso: "UA" },
	{ code: "+971", country: "阿联酋", iso: "AE" },
	{ code: "+598", country: "乌拉圭", iso: "UY" },
	{ code: "+998", country: "乌兹别克斯坦", iso: "UZ" },
	{ code: "+678", country: "瓦努阿图", iso: "VU" },
	{ code: "+58", country: "委内瑞拉", iso: "VE" },
	{ code: "+84", country: "越南", iso: "VN" },
	{ code: "+967", country: "也门", iso: "YE" },
	{ code: "+260", country: "赞比亚", iso: "ZM" },
	{ code: "+263", country: "津巴布韦", iso: "ZW" },
];

/**
 * 搜索国家代码
 * @param query 搜索关键词
 * @returns 匹配的国家代码列表
 */
export function searchCountryCodes(query: string): CountryCode[] {
	if (!query.trim()) {
		return countryCodes;
	}

	const lowercaseQuery = query.toLowerCase();

	return countryCodes.filter(
		(country) =>
			country.country.toLowerCase().includes(lowercaseQuery) ||
			country.code.includes(query) ||
			country.iso.toLowerCase().includes(lowercaseQuery),
	);
}

/**
 * 根据代码获取国家信息
 * @param code 国家代码
 * @returns 国家信息或undefined
 */
export function getCountryByCode(code: string): CountryCode | undefined {
	return countryCodes.find((country) => country.code === code);
}
